Repository SteeltoeOSS/Documentation, pull requests merged in 2021-07, with the labels that each got.

#184 RabbitMQHost & Docker
  Dockerfile
  README.md
  api-v2.json
  api/v3/messaging/rabbitmq-host.md
  api/v3/messaging/rabbitmq-intro.md
  guides/messaging/rabbitmq.md
Labels: documentation-pages, getting-started-guide

#185 Steeltoe 3.1 release article
  articles/index.md
  articles/releases/steeltoe-3-1-includes-event-driven-microservices-and-stream-based-data-Processing.md
Labels: blog

#186 OTel, metrics, heap dump, use 3.1.0
  api/v2/management/heapdump.md
  api/v3/bootstrap/index.md
  api/v3/circuitbreaker/hystrix.md
  api/v3/configuration/cloud-foundry-provider.md
  api/v3/configuration/config-server-provider.md
  api/v3/configuration/kubernetes-providers.md
  api/v3/configuration/placeholder-provider.md
  api/v3/configuration/random-value-provider.md
  api/v3/discovery/initialize-discovery-client.md
  api/v3/logging/dynamic-logging-provider.md
  api/v3/logging/index.md
  api/v3/logging/serilog-logger.md
  api/v3/management/heapdump.md
  api/v3/management/metric-observers.md
  api/v3/management/metrics.md
  api/v3/management/prometheus.md
  api/v3/management/springbootadmin.md
  api/v3/management/tasks.md
  api/v3/management/using-endpoints.md
  api/v3/messaging/rabbitmq-intro.md
  api/v3/security/credhub-api-client.md
  api/v3/security/jwt-authentication.md
  api/v3/security/mtls.md
  api/v3/security/redis-key-storage-provider.md
  api/v3/security/sso-oauth2.md
  api/v3/stream/rabbit-binder.md
  api/v3/stream/standalone-stream-rabbitmq.md
  api/v3/tracing/distributed-tracing-exporting.md
  api/v3/tracing/index.md
Labels: documentation-pages

#187 Blog Release Title/Breadcrumbs
  articles/index.md
  articles/releases/steeltoe-2-1-boosts-your-net-microservices-with-actuator-endpoints-distributed-tracing-and-deeper-support-for-the-frameworks-that-matter.md
  articles/releases/steeltoe-2-2-gives-your--microservices-a-boost.md
  articles/releases/steeltoe-2-4-boosts-dotnet-microservices-development.md
  articles/releases/steeltoe-3-0-packs-a-mighty-punch-with-many-new-features.md
  articles/releases/steeltoe-3-1-includes-event-driven-microservices-and-stream-based-data-Processing.md
  articles/releases/steeltoe-turns-2-0-adds-support-for-asp-net-core-2-0-credhub-and-a-sql-server-connector.md
Labels: blog

#191 Fix heapdump settings typo
  api/v3/management/heapdump.md
Labels: 3.x

#193 Distributed Tracing Namespace
  api/v2/tracing/index.md
  guides/cloud-management/distributed-tracing.md
Labels: documentation-pages, getting-started-guide
