Repository SteeltoeOSS/Documentation, pull requests merged in 2021-09, with the labels that each got.

#214 Update SBA client docs for 3.1.0
  api/v3/management/springbootadmin.md
Labels: documentation-pages, 3.x

#215 Document configurable JsonSerializerOptions
  api/v3/management/using-endpoints.md
Labels: documentation-pages, 3.x

#216 Eureka health & status paths can come from Management config
  api/v3/discovery/netflix-eureka.md
Labels: documentation-pages, 3.x

#217 Document configurable auth httpclient timeouts
  api/v3/security/jwt-authentication.md
  api/v3/security/sso-oauth2.md
  api/v3/security/sso-open-id.md
Labels: 3.x

#219 Fix code listing for LoggingConfig
  guides/cloud-management/endpoints-framework.md
Labels: 2.x

#220 Document which methods automatically add health contributors
  api/v2/connectors/microsoft-sql-server.md
  api/v2/connectors/mysql.md
  api/v2/connectors/postgresql.md
  api/v3/connectors/microsoft-sql-server.md
  api/v3/connectors/mysql.md
  api/v3/connectors/postgresql.md
Labels: documentation-pages, 2.x, 3.x
